// Action Types
export const COUNTER_INCREMENT = 'COUNTER_INCREMENT';
export const COUNTER_DECREMENT = 'COUNTER_DECREMENT';
export const COUNTER_INCREMENT_ANOTHER = 'COUNTER_INCREMENT_ANOTHER';
export const COUNTER_DECREMENT_ANOTHER = 'COUNTER_DECREMENT_ANOTHER';
export const DELIVER_PAYLOAD = 'DELIVER_PAYLOAD';
export const CLEAR_PAYLOAD = 'CLEAR_PAYLOAD';
